### ISSUE TITLE
Feature Request: support old versions of node

### ISSUE THREAD

**Issue by hyurl** [mikuso/node-pdo#1]
I'm very interesting in your project, but I've seen that it was written with new features (async/await) that only works on node 7.6 or later, I'm wondering if it is possible to rewrite some methods that compatible to old versions of node, 6.X or even 4.X probably.

**Comment by mikuso** [comment]
Support for Node 4.9.1 added in version 1.1.1 86e6c07f40e9b4076b6bf88469b77d1d27906af5
